### ISSUE TITLE
How to perform sub-pixel interpolation

### ISSUE THREAD

**Issue by limingzhu0916** [xrenaa/Deblur-by-Fitting#3]
Hi Xuanchi,
Thanks for your work. I notice that you applying sub-pixel interpolation to the motion vector. Could you tell more details about this？Or could you tell me which paper you are referring to？
I am also confused about the blur kernel generation. You mentioned in the paper ‘The scales of kernels we
choose are 21×21, 31×31, 41×41', does this mean the length of the motion vetcor l∈(0, 21), l∈(0, 31), l∈(0, 41)? And the orientation of the motion vetcor o∈[0, 180). If it is ture, there is kernel overlap here? 
I also wonder the dataset you used to train your model, could you please provide the dataset you used for train？

Thanks!

**Comment by xrenaa** [comment]
Hi,
Sorry for late reply. I am busy with conference ddls for the past months. 
For the sub-pixel interpolation, you can follow https://github.com/KupynOrest/DeblurGAN/tree/master/motion_blur.
You understand for kernel is correct and there may exist overlap for the kernel but the effect on the image is different due to the different l.
For the dataset, we plan to release the dataset and the code in June.

Best,
Xuanchi
